# Site settings
title: Kuang Qin
email: kuang.qin.hust@gmail.com
url: https://kuangami.github.io
description: Take a Journey from the Game World into Reality.

# google analytics
google_analytics: G-F54DWJC6W8

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Kuangami

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/kuang-qin/
  - title: github
    url: https://github.com/kuangami

# Build settings
markdown: kramdown
permalink: pretty
